### PR TITLE
Migrate Capacitor to 5

### PR DESCRIPTION
**Pull request by vovagorodok**
From August 31, 2023 Google Play Console accepts only min SDK 33: https://developer.android.com/google/play/requirements/target-sdk

Ported by instruction: https://capacitorjs.com/docs/updating/plugins/5-0

compilation successed

### CODE REVIEW

**Comment by veloce** [comment]
Thanks! Note that I don't maintain this project anymore, so I'm merging it but without testing .

**Comment by vovagorodok** [comment]
Sure mobilev2 has higher prio ) Can you release v5.0.0 of this capacitor? It is need in order to port blichess app to Capacitor 5

**Comment by veloce** [comment]
I'll try to do it tomorrow since I can't right now. You can ping me again if i forget

**Comment by vovagorodok** [comment]
Hi, I have also ported `capacitor-stockfish-variants` to Capacitor 5.

Please release also:
- https://github.com/veloce/capacitor-stockfish-variants/pull/1
- https://github.com/veloce/capacitor-sound-effect/issues/15

These three packages are needed for fully port lichobile from Capacitor 4 to 5. I have already ported lichobile locally

> `lichobile` with Capacitors 5 open possibility to release app on Google Play if some critical bugs will be fixed.
> also it opens possibility to release `blichess` on Google Play

**Pull request merged**
